//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDbContext : DbContext
    {
        public AppDbContext()
            : base("name=AppDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblCity> tblCity { get; set; }
        public virtual DbSet<tblClass> tblClass { get; set; }
        public virtual DbSet<tblDepartment> tblDepartment { get; set; }
        public virtual DbSet<tblRegisteredTo> tblRegisteredTo { get; set; }
        public virtual DbSet<tblRequestToJoin> tblRequestToJoin { get; set; }
        public virtual DbSet<tblRequestToJoinSuperStudent> tblRequestToJoinSuperStudent { get; set; }
        public virtual DbSet<tblStudent> tblStudent { get; set; }
        public virtual DbSet<tblSuperStudent> tblSuperStudent { get; set; }
        public virtual DbSet<tblTags> tblTags { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblTagsRequests> tblTagsRequests { get; set; }
        public virtual DbSet<tblTips> tblTips { get; set; }
    }
}
