//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegisteredTo
    {
        public string StudentId { get; set; }
        public int ClassCode { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<short> StudentRank { get; set; }
        public string RankDescription { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
